
mysql_root_password: nbusr123

mysql_databases:
  - name: '{{ nextcloud_db_name }}'
    state: present

mysql_users:
  - name: "{{ nextcloud_db_user }}"
    host: "%"
    password: '{{ nextcloud_db_password }}'
    priv: "{{ nextcloud_db_name }}.*:ALL"
  - name: "{{ nextcloud_db_user }}"
    host: "localhost"
    password: '{{ nextcloud_db_password }}'
    priv: "{{ nextcloud_db_name }}.*:ALL"
