- name: Create nextcloud setup path
  file: 
    dest: '{{ nextcloud_path }}'
    state: directory

- name: Check existence of index.php
  file: 
    dest: '{{ nextcloud_path }}/nextcloud/index.php'
    state: file
  register: _has_index
  failed_when: false
  check_mode: yes

- include: download-nextcloud.yml
  when: _has_index.state == 'absent'
    
